version: '3'

services:
  techpriest_bot:
    container_name: techpriest_bot
    image: h0d0user/techpriest_bot:latest
    restart: always
    environment:
      - API_ID=YOURAPIID
      - API_HASH=YOURAPIHASH
      - SESSION=YOURSESSION
    volumes:
      - "./settings.toml:/opt/settings.toml"
      - "./JustTalk.session:/opt/JustTalk.session"