version: '3'

services:

  search_mongodb:
    container_name: search_mongodb
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=searchdb
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - mongo_net
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  techpriest_bot:
    container_name: techpriest_bot
    image: h0d0user/techpriest_bot:latest
    restart: always
    environment:
      - API_ID=YOURAPIID
      - API_HASH=YOURAPIHASH
      - SESSION=YOURSESSION
      - TELEGRAM_BOT_TOKEN=TELEGRAM_BOT_TOKEN
      - MONGO_ROOT_USERNAME=username
      - MONGO_ROOT_PASSWORD=password
    networks:
      - mongo_net
    depends_on:
      - search_mongodb
    volumes:
      - "./settings.toml:/opt/settings.toml"
      - "./search_scheme.txt:/opt/search_scheme.txt"
      - "./search_places.txt:/opt/search_places.txt"
      - "./JustTalk.session:/opt/JustTalk.session"

networks:
  mongo_net: